### ISSUE TITLE
Cannot auto-complete header files as symlinks

### ISSUE THREAD

**Issue by RealSaltyFish** [MaskRay/ccls#676] opened 2020-07-21 15:54 UTC
### Observed behavior

In macOS, Homebrew stores header files for user-installed libraries in `/usr/local/Cellar/foo/include` and creates symlinks to these files under `/usr/local/include`. 

#### Scene 1
Under `/usr/local/include` there is a symlink `test.h` pointing to a file stored somewhere else.
Open an empty .cpp file, and enter `#include <test`. Nothing appears in the completion menu. I cannot perform auto-complete.
Manually complete it to `#include <test.h>` and everything works fine.

#### Scene 2
Under `/usr/local/include` there is a file `test.h`.
Open an empty .cpp file, and enter `#include <test`. Now I can auto-complete it to `#include <test.h>`.

#### Scene 3
Under `/usr/local/include` there is a symlink `testdir/` pointing to a directory elsewhere containing a file `test.h`.
Open an empty .cpp file, and enter `#include <test`. Nothing appears in the completion menu. I cannot perform auto-complete.
Enter more stuff: `#include <testdir/`. Now `test.h` appears in the completion menu and I can autocomplete it to `#include <testdir/test.h>`.

#### Scene 4
Under `/usr/local/include` there is a directory `testdir/` containing a file `test.h`.
Open an empty .cpp file, and enter `#include <test`. Now I can auto-complete it to `#include <testdir/` and then to `#include  <testdir/test.h>`.

### Expected behavior

In Scene 1, the expected behavior is supposed to be the observed behavior in Scene 2.
In Scene 3, the expected behavior is supposed to be the observed behavior in Scene 4.
In other words, header file auto-completion is supposed to work for symlinks too.

### Steps to reproduce

1. Install ccls via Homebrew. Use `--HEAD -i` to tell Homebrew to let you compile ccls instead of using the pre-compiled bottle (since the pre-compiled one is not working correctly).
2. Edit `coc-settings.json` to set `initializationOptions` to these:
```json
      {
	"cache": {
	  "directory": "/tmp/ccls"
	},
	"highlight": { "lsRanges" : true },
	"clang": {
	  "resourceDir": "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.3/",
	  "extraArgs": [
	    "-isystem",
	    "/Library/Developer/CommandLineTools/usr/include/c++/v1",
	    "-isystem",
	    "/usr/local/include"
	  ]
      }
```
3. Create the corresponding test files in `/usr/local/include`.
4. Create a new .cpp file somewhere and edit it using Neovim+coc.nvim+ccls
5. Try to auto-complete the header file you've just created.

### System information

* ccls version: 0.20190823.6
* clang version: Apple clang version 11.0.3 (clang-1103.0.32.59)
* OS: macOS 10.15.5 (with CommandLineTools installed)
* Editor: Neovim 0.4.3 (latest)
* Language client: coc.nvim 0.0.78-449dcad0b2 (latest)
* Also tested on VSCode 1.47.2 with official ccls plugin 0.1.29 (both latest), got the same result

**Comment by MaskRay** [comment] 2020-10-12 02:23
Duplicate of #639

**Closed by MaskRay** 2020-10-12 02:23 UTC
