### ISSUE TITLE
Not completing include directories set in .ccls

### ISSUE THREAD

**Issue by oblitum** [MaskRay/ccls#160] opened 2018-12-13 14:40 UTC
I'm using coc.nvim+ccls, it provides most headers for completion, but doesn't provide headers I set in `.ccls` flags, for example, I'm trying this:

```
%clang
-Wall
-Wextra
%c -std=gnu11
%cpp -pedantic
%cpp -std=c++17
%cpp -stdlib=libc++
%cpp -I/opt/src/GSL/include
%cpp -I/opt/src/range-v3/include
```

When I go about including `#include <rang|>`, I only get boost range headers from my system, even after `#include <range/|>`, simple no completion for `range/v3`. But code completion and diagnostics works for range-v3 symbols, just inclusion that fails.

**Comment by MaskRay** [comment] 2018-12-15 23:03
Close due to inactivity and I cannot reproduce.

**Comment by oblitum** [comment] 2018-12-15 23:45
Sorry, I didn't have time to test that suggestion yet (I just grab it from AUR). But I'd report it back.

**Comment by oblitum** [comment] 2018-12-15 23:46
Does it work for you with coc.nvim and like my testcase explains? Because just by using coc.nvim I can't make it work at all.

**Comment by MaskRay** [comment] 2018-12-16 00:03
I checked it with releases.llvm.org clang 7 not the AUR package.

**Comment by oblitum** [comment] 2018-12-16 00:06
I was referring to ccls from AUR, not clang. I mean, I'm just installing ccls by doing `aurman -S ccls`, not compiling it myself, for checking the snippet you pointed.

**Comment by oblitum** [comment] 2018-12-22 15:59
@MaskRay 

Same `.ccls`:

```
%clang
-Wall
-Wextra
%c -std=gnu11
%cpp -pedantic
%cpp -std=c++17
%cpp -stdlib=libc++
%cpp -I/opt/src/GSL/include
%cpp -I/opt/src/range-v3/include
```

I've put the following:

```cpp
    std::fstream f("/home/francisco/ccls-includes");
    for (auto &E : HeaderOpts.UserEntries) {
      std::string path =
          NormalizePath(ResolveIfRelative(entry.directory, E.Path));
      f << "user entry: " << E.Path << '\n';
      f << "normalized: " << path << '\n';
      f.flush();
```

`ccls-includes`:
```
user entry: /usr/local/include
normalized: /usr/local/include
user entry: lib/clang/7.0.1/include
normalized: /home/francisco/Projects/samples/c++/lib/clang/7.0.1/include
user entry: /include
normalized: /include
user entry: /usr/include
normalized: /usr/include
```

Notice how relative `lib/clang/7.0.1/include` became a bad normalized input.

This is the result when using cmake generated `compile_commands.json`, no issues:

```
user entry: /home/francisco/ccls/src/ccls-project/src
normalized: /home/francisco/ccls/src/ccls-project/src
user entry: /home/francisco/ccls/src/ccls-project/third_party
normalized: /home/francisco/ccls/src/ccls-project/third_party
user entry: /home/francisco/ccls/src/ccls-project/third_party/rapidjson/include
normalized: /home/francisco/ccls/src/ccls-project/third_party/rapidjson/include
user entry: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1
normalized: /usr/include/c++/8.2.1
user entry: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/x86_64-pc-linux-gnu
normalized: /usr/include/c++/8.2.1/x86_64-pc-linux-gnu
user entry: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/backward
normalized: /usr/include/c++/8.2.1/backward
user entry: /usr/local/include
normalized: /usr/local/include
user entry: /usr/lib/clang/7.0.1/include
normalized: /usr/lib/clang/7.0.1/include
user entry: /include
normalized: /include
user entry: /usr/include
normalized: /usr/include
```

**Comment by oblitum** [comment] 2018-12-22 16:00
I'm using the `project` branch.

**Comment by MaskRay** [comment] 2018-12-22 18:35
Can you try the `project` branch again?

The issue was that  `quote_dirs` overrode `angle_dirs` so you don't get completion when `<` was used, `"` should work. The latest change unifies `quote_dirs` and `angle_dirs` to a single `search_dir2kind`.

**Comment by oblitum** [comment] 2018-12-22 18:55
@MaskRay I've checked, it's working now.

**Comment by MaskRay** [comment] 2018-12-22 19:21
Fixed by #171

**Closed by MaskRay** 2018-12-22 19:21 UTC
Labels: bug

**Comment by oblitum** [comment] 2018-12-23 13:09
Hi @MaskRay, I got another issue after this fix, it's working great for the previous flags, but if I remove `-stdlib=libc++` I stop getting include suggestions for `<iostream>` and other basic std headers.

```
~/P/s/c++ ❯❯❯ cat .ccls
%clang
-Wall
-Wextra
%c -std=gnu11
%cpp -pedantic
%cpp -std=c++17
```

**Comment by MaskRay** [comment] 2018-12-23 17:57
> I got another issue after this fix, it's working great for the previous flags, but if I remove `-stdlib=libc++` I stop getting include suggestions for `<iostream>` and other basic std header

Isn't it the opposite? Check what `clang++ -fsyntax-only -v -xc++ /dev/null -stdlib=libc++` tells you, and also read https://github.com/MaskRay/ccls/issues/125#issuecomment-440137433

`-stdlib=platform` (default) uses `libstdc++` on most Linux, and `libc++` on Mac OS X>=10.9, FreeBSD>=10, NetBSD>=7, ...

**Comment by oblitum** [comment] 2018-12-23 18:06
No no, it's not the opposite, it's in fact what I've stated, __with__ `-stdlib=libc++` (which is in fact what I use in general while completing), it works. Removing just that line and leaving the rest like the `cat` above, I don't get completion for std headers anymore.

**Comment by oblitum** [comment] 2018-12-23 18:07
I'm leaving now, so will be able to answer just a few hours later.
