### ISSUE TITLE
False-positive "redefinition" error in .hpp/.inl file pairs

### ISSUE THREAD

**Issue by andreasxp** [MaskRay/ccls#621] opened 2020-04-26 16:12 UTC
I have many pairs of files like this:
```C++
//example.hpp
#pragma once
template <class T>
class Example {
    ...
}

#include "example.inl"
```
```C++
//example.inl
#pragma once
#include "example.hpp"

template <class T>
Example<T>::Example() {
	...
```
i.e. template classes that have their members definition in a separate `.inl` file that includes the `.hpp`.
Notice that despite the header including the inl and the inl including the header, there's no redefinitions because both files are guarded by `pragma once`. The program compiles with no errors.

Despite this, ccls reports a redifinition error with a previous definition in the same place.
![example of error](https://i.imgur.com/9lErGvH.png)

Is there a way to fix this? Also, if this is not fixable, is there a switch that disables specific errors in ccls?

* ccls version: 0.20190823.6-16-gc5acf620
* clang version: 9.0.1 from MSYS2
* OS: Windows 10
* Editor: VSCode

**Comment by findNextStep** [comment] 2020-04-27 02:21
It may be same issure as https://github.com/MaskRay/ccls/issues/500

**Comment by MaskRay** [comment] 2020-07-05 23:22
Thanks for the analysis!

Duplicate of #500.

**Closed by MaskRay** 2020-07-05 23:22 UTC
