### ISSUE TITLE
Incorrect errors reported in flymake

### ISSUE THREAD

**Issue by cody-addison** [MaskRay/ccls#188] opened 2019-01-02 20:45 UTC
I have a C++ file that compiles cleanly, but there are several errors reported by flymake. I enabled lsp-print-io and can see the errors reported in message with a method of "textDocument/publishDiagnostics". Compiling the file using the command in the compile_commands.json file succeeds without any errors. Let me know if there is any additional information you require to debug this issue.

**Comment by madscientist** [comment] 2019-01-03 03:08
There's not much we can do to help without even a hint as to what kinds of errors you're seeing.  But, note that ccls does not use the full command line in compile_commands.json to parse your file: in particular ccls is using the Clang+LLVM shared library parser so if your compile_commands.json file specifies some compiler other than Clang, such as GCC, etc. that compiler is not being used.  ccls does take all the flags (-I, -D, etc.) from the compile line and uses them with whatever version of libLLVM it was built with.

**Comment by madscientist** [comment] 2019-01-03 03:33
I can't really help with MacOS or homebrew issues.  I've only used ccls on Linux and I've built it myself from the latest Git content.  I recommend you enable logging by starting the ccls server with `--log-file=/tmp/ccls.out -v=1` and examine the command line that ccls is using when parsing.  There may be more useful information there than can be returned to the client.  Make sure the flags you expect to see are all there.  Make sure that the Clang resource directory shown in the log output exists and that it contains `include/stddef.h` (plus lots of other header files).

**Comment by cody-addison** [comment] 2019-01-03 03:47
The resource directory is a tmp directory which doesn't exist.

/private/tmp/ccls-20190102-27640-1splkmb/Release/clang+llvm-7.0.0-x86_64-apple-darwin/lib/clang/7.0.0

Maybe this is a problem with the brew build? I'll dig a little deeper to see what is going on.

**Comment by madscientist** [comment] 2019-01-03 04:00
Could be.  ccls definitely needs to be able to find these files or parsing will certainly fail.  Anyone attempting to create a package of ccls based on the downloaded Clang+LLVM needs to include the resource directory and build ccls so it can be found.

If you can find a correct resource directory you can tell ccls to use it with the clang.resourceDir initialization option.

**Comment by cody-addison** [comment] 2019-01-03 04:16
Thanks for your help! The resource directory was indeed the problem. I built ccls myself and the resource directory is now correct and the compilation errors are gone.

**Comment by madscientist** [comment] 2019-01-03 04:36
Nice!  If there's some sort of issue tracker for homebrew you might want to try to log an issue there about this.

**Comment by MaskRay** [comment] 2019-01-03 15:53
Duplicate of https://github.com/MaskRay/ccls/issues/37

https://github.com/MaskRay/ccls/wiki/FAQ : 

> Check Clang_EXECUTABLE in your CMakeCache.txt. The output of command $Clang_EXECUTABLE -print-resource-dir will be passed to -DDEFAULT_RESOURCE_DIRECTORY. Make sure you can locate include/stddef.h in the resource directory.

**Closed by MaskRay** 2019-01-03 15:53 UTC
Labels: duplicate, invalid
