### ISSUE TITLE
Build fails with clang 6.0.1

### ISSUE THREAD

**Issue by thmo** [MaskRay/ccls#119] opened 2018-11-12 23:01 UTC
On Fedora 28, with 0.20181111:
```
$ CC=clang CXX=clang++ cmake -H. -BRelease -DCMAKE_INSTALL_PREFIX=/usr  -DUSE_SHARED_LLVM=on -DSYSTEM_CLANG=On -DLLVM_ENABLE_RTTI=on
-- The CXX compiler identification is Clang 6.0.1
-- Check for working CXX compiler: /usr/lib64/ccache/clang++
-- Check for working CXX compiler: /usr/lib64/ccache/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Using system Clang
-- Found Clang: /usr/lib64/libclangIndex.so (found suitable version "6.0.1", minimum required is "6.0.0") 
-- Found Curses: /usr/lib64/libcurses.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: .../ccls/Release
```

```
$ cmake --build Release
Scanning dependencies of target ccls
[  2%] Building CXX object CMakeFiles/ccls.dir/third_party/siphash.cc.o
[  4%] Building CXX object CMakeFiles/ccls.dir/src/clang_complete.cc.o
.../ccls/src/clang_complete.cc:274:58: error: no member named 'get' in 'llvm::MemoryBuffer'
    preamble->Preamble.AddImplicitPreamble(*CI, FS, Buf->get());
                                                    ~~~  ^
1 error generated.
gmake[2]: *** [CMakeFiles/ccls.dir/build.make:76: CMakeFiles/ccls.dir/src/clang_complete.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/ccls.dir/all] Error 2
gmake: *** [Makefile:130: all] Error 2
```

**Comment by MaskRay** [comment] 2018-11-13 04:43
Thanks, it was caused by a recent change to use clang `#include` completion when available (clang >= 8). Fixed in HEAD.

I am wondering when Fedora will have clang >= 7 :)

**Closed by MaskRay** 2018-11-13 04:43 UTC

**Comment by thmo** [comment] 2018-11-13 06:56
> I am wondering when Fedora will have clang >= 7 :)

Fedora 29 and later have :)
Thanks for fixing.

**Comment by MaskRay** [comment] 2018-11-13 06:58
Does the Ubuntu 14.04 or 16.04 prebuilt archive work on Fedora 28?

https://github.com/MaskRay/ccls/wiki/Build#cmake-options

`cmake -GNinja -H. -BBundled -DSYSTEM_CLANG=on -DCMAKE_PREFIX_PATH=$PWD/build/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-14.04`
