### ISSUE TITLE
Use CMake FetchContent instead of submodules [proposal]

### ISSUE THREAD

**Issue by myrgy** [MaskRay/ccls#322] opened 2019-03-13 08:41 UTC
New CMake has one useful feature - fetch repository during configuration.
It might be a neat replacement to git submodules

https://cmake.org/cmake/help/latest/module/FetchContent.html
https://cliutils.gitlab.io/modern-cmake/chapters/projects/fetch.html

**Comment by MaskRay** [comment] 2019-03-13 09:53
Thanks for sharing this!

Duplicate of https://github.com/MaskRay/ccls/pull/306

It may be worth doing that at some point but it is too early now..

**Closed by MaskRay** 2019-03-13 09:53 UTC
