### ISSUE TITLE
Standard library headers not recognised

### ISSUE THREAD

**Issue by gcohara** [MaskRay/ccls#629] opened 2020-05-01 20:10 UTC
Hi,

I'm aware that there's an entry in the FAQ for this exact issue, but I couldn't really figure out what I was supposed to do.
I installed via `brew install ccls`, having updated llvm which was installed via `brew install llvm`.
Then, going into Emacs, navigating to a C file, and using `M-x eglot` results in Flycheck highlighting `#include <stdio.h>` etc, with this as the error:
`ccls cannot open file '/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0/include/stdio.h`.

I think that I'm supposed to change the directory that ccls is looking for header files in, but I'm not really sure how to do this.
It might be worth noting that I am fairly new to C, and so far don't use CMake etc, and tend to just use a simple `make` file.

### System information

* ccls version (`git describe --tags --long`):  <unknown>
* clang version: 10.0.0
* OS: macOS 10.15.4
* Editor: Emacs
* Language client (and version): Eglot

**Comment by sunbubble** [comment] 2020-05-02 13:21
Could this be related to https://github.com/MaskRay/ccls/issues/622?

**Comment by gcohara** [comment] 2020-05-09 17:22
It looks like it could be - I'll try and do the workaround in that thread within the next couple of days and report back.

**Comment by tleplaearthur** [comment] 2020-06-07 05:12
was this ever solved?

**Comment by sunbubble** [comment] 2020-06-07 09:41
Not to my knowledge. The workaround did the trick though.

**Comment by gcohara** [comment] 2020-06-07 09:56
I'm not sure to be honest. I ended up just using clangd. I'd be happy to see if I could reproduce the issue if people like.

**Comment by tleplaearthur** [comment] 2020-06-07 14:42
I tried the workaround but then I got an error like 

The C++ compiler
    "/Users/timothyleplae-arthur/Downloads/clang+llvm-10.0.0-x86_64-apple-darwin/bin/clang"
  is not able to compile a simple test program.

This mappens when I call cmake.

**Comment by xceejay** [comment] 2020-06-11 17:15
![bugccls](https://user-images.githubusercontent.com/44475401/84418688-0a8d4380-ac07-11ea-9918-c5234fda0b4f.png)

same it cannot recognise std libs

**Comment by MaskRay** [comment] 2020-07-05 22:59
Duplicate of #622 

macOS has some strange settings...

**Closed by MaskRay** 2020-07-05 22:59 UTC
