### ISSUE TITLE
ccls: `use of undeclared identifier 'printf'` despite `<cstdio>` including just fine

### ISSUE THREAD

**Issue by thorlucas** [MaskRay/ccls#743] opened 2020-12-28 05:10 UTC
### Observed behavior

I was able to convince ccls to find `cstdio` by using the method [here](https://github.com/MaskRay/ccls/issues/742). However, despite finding (and completing) the path for `cstdio` just fine, we still get `use of undeclared identifier 'printf'`:

<img width="1215" alt="Screen Shot 2020-12-27 at 9 05 10 PM" src="https://user-images.githubusercontent.com/25698466/103190769-36140a80-4887-11eb-8749-b5bfbf315cce.png">

### Steps to reproduce

I built and installed ccls succesfully with no errors according to the Wiki.

```
// .ccls
clang
%cpp --std=c++14
-I/usr/local/Cellar/rdkit/2020.09.1/include/rdkit
-L/usr/local/Cellar/rdkit/2020.09.1/lib
-lRDKitSmilesParse
```

CocConfig

```
{
	"languageserver": {
		"ccls": {
			"command": "ccls",
			"filetypes": ["c", "cpp", "objc", "objcpp"],
			"rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
			"initializationOptions": {
				"cache": {
					"directory": "/tmp/ccls"
				},
				"clang": {
					"resourceDir": "/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0",
					"extraArgs": [
						"-isystem",
						"/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1"
					]
				},
			}
		}
	}
}

```

### System information

```
ccls version <unknown>
clang version 11.0.0
```

I ran the `git clone --depth=1 --recursive https://github.com/MaskRay/ccls`, so whatever that points to as of today. `git describe --tags --long` returns `fatal: No names found, cannot describe anything.`

* OS: macOS 11.1
* Editor: neovim with CoC

**Comment by findNextStep** [comment] 2020-12-28 06:16
what if you remove the line up
```cpp
```

**Comment by thorlucas** [comment] 2020-12-28 08:17
I will try when I get home but I should note that the above line shouldn’t be causing an error either. The program compiles and runs just fine. The above error is caused because ccls seems to be unable to distinguish the overload, so it’s saying that it expects two arguments but found only one. Even though ccls actually was able to provide a completion for the signature that takes only one argument.

**Comment by thorlucas** [comment] 2020-12-28 09:36
Yep 
<img width="1457" alt="Screen Shot 2020-12-28 at 1 36 26 AM" src="https://user-images.githubusercontent.com/25698466/103204854-1c85b980-48ad-11eb-9f9a-b35e03d8127f.png">

**Comment by thorlucas** [comment] 2020-12-28 12:05
I managed to solve the `printf` problem by including a bunch of extra `-I` flags:

```
-I/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
-I/Library/Developer/CommandLineTools/usr/include
```

However, the issue with `ccls` complaining that `SmilesToMol` has too few arguments persists. Even though the *top completion suggestion* is the overloaded func with only one argument, it still insists there should be two arguments.

**Comment by thorlucas** [comment] 2020-12-30 00:01
Additionally, I don't think I should have to include these paths as these are standard search paths for clang.

**Comment by MaskRay** [comment] 2021-01-09 19:18
Duplicate of #716

This is a known issue on macOS where the standard search directories need to be explicitly specified.

**Closed by MaskRay** 2021-01-09 19:18 UTC
