### ISSUE TITLE
[proposal] "create implementation"

### ISSUE THREAD

**Issue by myrgy** [MaskRay/ccls#273] opened 2019-02-19 13:26 UTC
Hi MaskRay,

Thanks a lot for great tool!

It might be great to have ability "create implementation" call.
It should create method in corresponding cpp file.

Another useful refactoring tool is "Move to cpp" 

Thank you in advance!

**Comment by MaskRay** [comment] 2019-02-24 13:24
Duplicate of https://github.com/MaskRay/ccls/issues/223

**Closed by MaskRay** 2019-02-24 13:24 UTC
