### ISSUE TITLE
Does ccls support multiple compile_commands.json?

### ISSUE THREAD

**Issue by thekenu** [MaskRay/ccls#653] opened 2020-06-16 01:17 UTC
Here are some things you should try before filing a bug report:

+ For client issues related to [emacs-ccls](https://github.com/MaskRay/emacs-ccls) or [vscode-ccls](https://github.com/MaskRay/vscode-ccls), report in their own repository.
+ For build problems, check https://github.com/MaskRay/ccls/wiki/Build
+ Check https://github.com/MaskRay/ccls/wiki/Debugging
+ Check [the FAQ](https://github.com/MaskRay/ccls/wiki/FAQ) to see if your issue is mentioned.

If none of those help, remove this section and fill out the four sections in the template below.

---

### Observed behavior

I have a CMake project with two build configurations, and as a result I have two different `compile_commands.json`. How can I make `ccls` use both of my `compile_commands.json`? I am using `ccls` through `Coc` and they pointed out that is an issue on the `ccls` side.

### Expected behavior
Some way to add a list of compile_commands.json to `ccls`

### System information

* ccls version (`git describe --tags --long`): 
* clang version: 8.0.0
* OS: Ubuntu 18.04
* Editor: 
* Language client (and version):

**Comment by MaskRay** [comment] 2020-06-27 04:12
Duplicate of #527 

Search for "workspaceFolders" in existing issues. For example, #479 (comment)

As an alternative (without workspace folders, concatenate the entries of all compile_commands.json and create a unified one. Don't worry about missing entries. ccls can infer the command line of a file that does not exist in compile_commands.json

**Closed by MaskRay** 2020-06-27 04:12 UTC
