### ISSUE TITLE
Arrow operator exposes methods available by value

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/ccls#207] opened 2019-01-15 17:51 UTC
There is smart dot operator handling in ccls which lets you call methods of smart pointer targets. But if you use arrow operator you see smart pointer methods in the first place for some reason.

![image](https://user-images.githubusercontent.com/7345761/51199212-46838280-1907-11e9-8552-b5a07ebc6117.png)

```
struct A {
    void m1();
};

struct B : private A {
    void m2();
};

void foo () {
    std::unique_ptr<A> ap;
    ap->
```

**Comment by MaskRay** [comment] 2019-01-16 01:55
Duplicate of https://github.com/MaskRay/ccls/issues/99

An initialization option to disable it may be useful.

**Comment by Riatre** [comment] 2019-01-16 16:43
This is actually a valid bug caused by https://github.com/MaskRay/ccls/commit/ac2d921ab91d04ce22fdb9f7de8ece42c80d5902, ccls should put smart pointer methods *after* methods of the wrapped object, and it did try to do so. However VSCode sorts the completion result according to `(score, sortText)` again, where `score` is a fuzzy matching score between `filterText` and user input computed by VSCode.

For example, consider these two results for `file->|`:

```json
[{
        "label": "ToFunc",
        "kind": 2,
        "detail": "ToFunc(Usr usr) -> IndexFunc &",
        "sortText": "   !",
        "filterText": "ToFunc",
        "insertTextFormat": 1,
        "textEdit": {
          "range": {
            "start": {
              "line": 472,
              "character": 8
            },
            "end": {
              "line": 472,
              "character": 8
            }
          },
          "newText": "->ToFunc("
        }
},
{
        "label": "get",
        "kind": 2,
        "detail": "get() const -> pointer",
        "sortText": "   9",
        "filterText": "->get",
        "insertTextFormat": 1,
        "textEdit": {
          "range": {
            "start": {
              "line": 472,
              "character": 6
            },
            "end": {
              "line": 472,
              "character": 8
            }
          },
          "newText": ".get()"
        }
}]
```

VSCode takes the text between `.textEdit.range.start` and `.textEdit.range.end` as "user input", for `ToFunc` it would be empty, for `get` it would be "->", we have to include this part in `filterText`, otherwise results overlapping with existing texts will be filtered out. This was done in the commit mentioned before. However, because `LCP("ToFunc", "") = 0`, `LCP("->get", "->") = 2`, the fuzzy matching score of `get` is larger than the score of `ToFunc`, so it will always be put at the top of the completion result, which is not expected.

**Comment by MaskRay** [comment] 2019-01-18 04:37
We can also just disable `textEdit` (`CCOpts.IncludeFixIts = false;`) in `textDocument/completion` results as clang only supports `->` <=> `.` for now and it does not seem very useful.

**Comment by Yanpas** [comment] 2019-01-18 07:13
Agree

**Comment by Riatre** [comment] 2019-01-18 15:53
> Is score a VSCode internal?
Yes.

> Can we make assumptions on the order how VSCode applies textEdit and additionalTextEdits that is not regulated in the spec?

VSCode applies `textEdit` first, then all `additionalTextEdits` sequentially. IIRC all the ranges returned by Clang is based on the state before any edits, so we still have to make some adjustments. I agree that may lead to a cleaner workaround, I'm going to try this.

**Comment by Riatre** [comment] 2019-01-29 17:44
I have tried this and the same thing described in https://github.com/Microsoft/language-server-protocol/issues/543 happened. It looks like LSP explicitly mentioned that having `textEdit` and `additionalTextEdits` on the same line is unsupported, but VSCode do accept such responses and `additionalTextEdits` gets applied first. (Which is strange because I can see these edits pops earlier in undo stack ?!)

So we can either:
1. Swap `textEdit` and `additionalTextEdits`.
2. Changing the `range` of `textEdit` according to the assumption that `additionalTextEdits` gets applied first.

I'm sure 1 is going to break other clients, and I'm not sure whether 2 is cleaner than #210 since if you change `range`, you have to also change `filterText` accordingly for the same reason.

**Closed** 2019-01-30 15:21 UTC
Labels: duplicate

**Comment by MaskRay** [comment] 2019-01-30 15:24
I agree that `additionalTextEdits` may be applied before `textEdit`.. #210 doesn't look too bad then as other clients may apply `textEdit` before `additionalTextEdits`..

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestController.ts#L235
