### ISSUE TITLE
on mac, cmake module file for RapidJson provides RAPIDJSON_INCLUDE_DIRS instead of RapidJSON_INCLUDE_DIRS

### ISSUE THREAD

**Issue by Frefreak** [MaskRay/ccls#455] opened 2019-08-04 03:45 UTC
### Observed behavior

```
cmake .. -DUSE_SYSTEM_RAPIDJSON=ON
```
returns
```
-- RapidJSON found. Headers: /usr/local/Cellar/rapidjson/1.1.0/include
-- Configuring done
-- Generating done
```
but `make` returns error `fatal error: 'rapidjson/fwd.h' file not found`

The **CMakeLists.txt** assumes the include path of rapidjson be stored in `${RapidJSON_INCLUDE_DIRS}` but is actually `${RAPIDJSON_INCLUDE_DIRS}`. The relevant  cmake module is located in **/usr/local/lib/cmake/RapidJSON/RapidJSONConfig.cmake** and provided by rapidjson package (`brew install rapidjson`). Nothing big but definitely an issue which prevents the building from working "out of the box" on mac. 

### Expected behavior

build complete successfully.

### Steps to reproduce

```
cmake .. -DUSE_SYSTEM_RAPIDJSON=ON
make
```

### System information

* ccls version (`git describe --tags --long`): 0.20190314.1-21-g8b033217
* clang version: clang version 8.0.0 (tags/RELEASE_800/final)
* OS: MacOS mojave 10.14.6

**Comment by MaskRay** [comment] 2019-08-04 11:40
Duplicate of https://github.com/MaskRay/ccls/pull/383

**Closed by MaskRay** 2019-08-04 11:40 UTC
