### ISSUE TITLE
symbols from newly included header not showing

### ISSUE THREAD

**Issue by Aayush04** [MaskRay/ccls#190] opened 2019-01-04 12:50 UTC
After staring ccls server if i include a new header in the file then i am unable to find symbols from this newly included header but i can find symbols from the headers which are already included while starting ccls server.

Detailed Description:
I am using ccls lsp with monaco-language client (https://github.com/TypeFox/monaco-languageclient ).  Running the ccls server as

`ccls --init='{"cacheFormat":"json", "index": {"onChange": true, "trackDependency":2}}'`

and project structure is:

```
MyProject/
MyProject/Script.cpp
MyProject/.ccls
```

.ccls file content is:

```
%clang
%c -std=gnu11
%cpp -std=gnu++14
%objective-c %objective-cpp -DGNUSTEP
%c %cpp -DFOO
-pthread

# Includes
-I/usr/include/
-I/usr/local/include/
```

Script.cpp file content is:
```
#include<stdio.h>
#include<math.h>

int main( )
{
    printf ( "Hello World");
}
```

Now, i can able to get function from math.h library for autoCompletion in editor. But if add a new header like string.h in my file. I am unable to get autoCompletions like for function strcmp() .

On running ccls server it is also creating cache files in directory`MyProject/.ccls-cache` And on adding string.h in my file, index file for this also getting created in directory`MyProject/.ccls-cache` but still autoCompletion not working for this. That is I am unable to get any symbol or funcitons from string.h library in `textDocument/completion` result.

```
ls /home/workspace/MyProject/.ccls-cache/\@\@home\@workspace\@MyProject/ | grep string.h
@usr@include@string.h
@usr@include@string.h.json
@home@lsp@ccls@Release@clang+llvm-7.0.0-x86_64-apple-darwin@include@c++@v1@string.h
@home@lsp@ccls@Release@clang+llvm-7.0.0-x86_64-apple-darwin@include@c++@v1@string.h.json
```

@MaskRay, Any idea what I am doing wrong here?

**Comment by MaskRay** [comment] 2019-01-07 07:00
Is this issue a duplicate of https://github.com/MaskRay/ccls/issues/191 ?

**Comment by Aayush04** [comment] 2019-01-11 11:30
> Is this issue a duplicate of #191 ? I think this is a misconfiguration on Mac OS X but I don't use Mac thus cannot verify.

I think it's not. As autocompletion working properly while including the header. But symbols or methods from this newly added header are not coming on hitting ctlr+space. 
Same problem coming when i installed all this in ubuntu docker container. So, this should not an issue with Mac OS X.

**Closed** 2019-01-13 10:39 UTC

**Comment by MaskRay** [comment] 2019-01-13 10:43
I was aware of the issue (imprecise preamble), saving the document would bring the preamble up to date. Language clients may cache completion results (coc.nvim company-lsp ...) thus I choose to rebuild preamble in the `CompletionMain` if it gets stale to avoid inaccurate results.
