### ISSUE TITLE
Always reindexing on startup in VS Code

### ISSUE THREAD

**Issue by torokati44** [MaskRay/ccls#718] opened 2020-11-09 20:06 UTC
#### Observed behavior

Every time I start VS Code in a project folder, ccls starts indexing the codebase from scratch.

#### Expected behavior

The index built previously is discovered and used, without rebuilding it at start.

#### Steps to reproduce

Optional: Delete the .ccls-cache subfolder in the project folder.
Open VS Code with ccls enabled in a project folder, having compile_commands.json present
Wait for the indexing to finish completely.
Exit VS Code.
Open VS Code again in the same project folder.
Discover that the indexing is started again for no apparent reason.

#### System information

* clang version: 11.0.0 (Fedora 11.0.0-1.fc33)
* OS: Fedora 33, x86_64
* Editor: VS Code 1.51.0
* Language client (and version): vscode-ccls v0.1.29

I have bisected this bug, and it seems cb08df44aa552d3120e2e1d317f9aaafdf2cfd65 is the first affected commit.
I have not investigated the change any further. I can provide further logs or information upon request.

**Comment by torokati44** [comment] 2020-11-09 20:59
Indeed, simply reverting that single commit (cb08df44aa552d3120e2e1d317f9aaafdf2cfd65) from current master (87ddcc443fe5f0941efd068aebd7b24d45d01945) resolves this issue.

**Comment by madscientist** [comment] 2020-11-11 17:47
Is this related to issue #682 ?  That issue initially at least also pointed to commit cb08df4 as the problem...

**Comment by torokati44** [comment] 2020-11-11 20:19
I have localised the problem to `std::string pathFromFileEntry(const FileEntry &file)` in `clang_to.cc`.

Sometimes `file.getName()` returns strings like: `/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/cstring`
Paths like these seem to mis-use the strange fact that `/../` == `/` (there is a loop at the root of the FS) [1]

The simple string-processing functions used (which there are many of) might not handle this correctly?
And the order in which these are called has changed in cb08df4.
I have no idea where these peculiar file names come from, and if they should look like that; or maybe whether they are the result of a different glitch somewhere else...

[1]: This was new to me as well, but see the section titled "File structure" here: https://medium.com/better-programming/how-unix-works-everything-you-were-too-afraid-to-ask-f8396aeb2763

**Comment by torokati44** [comment] 2020-11-11 21:08
What was the reason for no longer relying on `file.tryGetRealPathName()`?
That would almost be a trivial quick-path in `pathFromFileEntry`, isn't that so?
At least it happens to not return any paths starting with `/../` in my case, and judging by the name, it never should.

**Comment by torokati44** [comment] 2020-11-11 21:49
The current `pathFromFileEntry` code always starts out with `file.getName()`, which will look, for example, like this:
`/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/iterator`

The first thing it does with it is passing it through `normalizePath`.
Turns out, `normalizePath` just delegates to `llvm::sys::path::remove_dots`, which, as far as I've seen, does work fine on paths starting with `/../`.
**However**, the assumption that _all_ `foobar/../` parts can be "optimized out" with simple string processing is wrong. Because of symbolic links, of course.

On my system, `/lib/` is a symbolic link to `/usr/lib/`, I believe as a result of the ["/usr unification"](https://lwn.net/Articles/483921/) effort going on in the Fedora project (and perhaps many other places). Notice how the reporter of #683 also uses Fedora.
This is not the case on (at least the 18.04 release of) Ubuntu.

So, `normalizePath` will _incorrectly_ perform this transformation (I guess anyways, the result is verified):
`/../lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/iterator`
`/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/iterator`
`/lib/gcc/x86_64-redhat-linux/../../../include/c++/10/iterator`
`/lib/gcc/../../include/c++/10/iterator`
`/lib/../include/c++/10/iterator` <-- this is where it goes wrong, `/lib` is a symbolic link, cannot be thrown out like this
`/include/c++/10/iterator`

This does seem _stringically_ fine, except for that one part near the end. This is not the fault of `llvm::sys::path::remove_dots` of course, it does what it says, it just shouldn't be used right here, for this.

The first thing `file.getName()` should pass through is `realPath`, in my opinion. This was not the case in the old code either, but the buggy case was never taken, because `tryGetRealPathName()` made it unnecessary. I also think that this should still be used.

**Comment by cbsirb** [comment] 2020-12-04 09:29
I had the same issue, and indeed the problem is in `normalizePath`, more specifically in `llvm::sys::path::remove_dots`. It seems that resolving '/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/algorithm' to '/include/c++/10.2.0/algorithm' is done without resolving any symlinks (which is the issue after all).

The fix is pretty simple in `pathFromFileEntry` but I don't know which one to apply (maybe @MaskRay can help us here):
1. Either resolve the symlink at the beginning of the function (before the first `normalizePath`) and work only with that afterwards
2. When calling `realPath(ret)` instead call `realpath(file.getName().str())` since `ret` is the path which is resolved wrongly.

**Comment by MaskRay** [comment] 2020-12-20 03:35
Sorry for my late reply. cb08df4 was buggy for some distributions where `getName()` returns `/../*` style names for some /usr header files. Fixed by ca95f48a53b91be9646b6ab4943f4af3db8367f7

**Closed by MaskRay** 2020-12-20 03:35 UTC

**Comment by torokati44** [comment] 2020-12-20 13:55
It's all right. The fix indeed seems to work for me. Thanks!
