### ISSUE TITLE
Enhancement: idea to allow defering full indexing?

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#180] opened 2018-12-27 01:14 UTC
Because full indexing of my projects takes a long time and a lot of CPU, and because I create and delete a number of worktrees quickly where I make smaller, superficial changes that don't need to be fully indexed, I'm looking for ways to reduce or defer indexing until it's needed.  I understand that in this mode queries that rely on global reference information will be missing or incomplete.

I'm aware of `initialBlacklist`, which is very useful in some situations, but was thinking about something more specifically targeted at this problem.

An idea would be for a new configuration option introducing a "distance" parameter.  If the distance value is 0 (the default), then all files in the project are indexed.  If the value is 1, then only the file which is visited by the editor would be indexed (equivalent to blacklisting all files, if I understand that behavior correctly).  If the value is 2, then when a file is visited that file plus files one "distance" removed from that file are indexed.  Etc.

By "distance" I mean a logical proximity to the visited file.  I would define this as "the source files that define the declarations in a header file included by the original source file".  So for example if we visit a file `foo.c` and it includes a file `bar.h` which declares classes or functions and those classes or functions are defined/implemented in a file `bar.c`, then `bar.c` is one "distance" removed from `foo.c`.   If `bar.c` includes `blah.h` and `blah.h` declares classes or functions which are defined in `blah.c`, then `blah.c` is one "distance" removed from `bar.c` and **two** "distances" removed from `foo.c`.

Of course there's no way to be sure, based on the current information available (without indexing!!), which source file defines the classes or functions declared in a given header file.  However, I think it's a reasonable heuristic to use file names.  Almost every project of any significant size (that would need to worry about reduced indexing) follows a convention that a file `xyzzy.c` (or `xyzzy.cpp` or `xyzzy.cc`) defines the classes / functions declared in `xyzzy.h` (or `xyzzy.hpp`).

So then, the algorithm for this parameter would be something like:

1. server receives a request for a new source file X
2. set `sources` to `[X]`
3. for (i = distance; i > 0; --i):
   * set `newsources` to `[]`
   * for each `file` in `sources`:
       * index `file`
       * for each header found while indexing `file`, check to see if it has a corresponding source file (by name) which hasn't been indexed.  if so, add to `newsources`
   * set `sources` to `newsources`

The check for source file could be as simple as: chop the path and extension (after the final `.`) to get _base_ then add all files found in the project named _base_ plus a list of source extensions (`.c`, `.cpp`, `.cc`).  If we index a few too many files it's not a big deal, and most projects won't have the same base name file multiple times anyway as it's confusing for developers (and some build systems!)

Setting "distance" to "2" using this algorithm should be sufficient to allow "jump to definition" capability for any symbol in a file we visit, without requiring the full project to be indexed up-front.  At least, for development environments following the most common organizational models.  It wouldn't allow accurate "list all callers of this method"-style capability of course, unless you used "distance 0" (or otherwise caused everything to be indexed).

**Comment by MaskRay** [comment] 2018-12-27 04:05
The difference between the initialization options `index.blacklist` and `index.initialBlacklist` is that the latter allows indexing after you open the files.

When you invoke `textDocument/definition` in `foo.c` on an identifier declared by `bar.h`, it'll get you to `bar.h` (as if `textDocument/declaration` is used). You may use `projectile-find-other-file` to visit `bar.c` (other editors have similar heuristic rules to find "other/alternative" files).

Next time when you invoke `textDocument/definition` in `foo.c` on the same identifier, it'll jump to the definition in `bar.c`.

Do you find it still a bit inconvenient?

**Comment by Yanpas** [comment] 2018-12-27 06:21
Yeah, I don't like opening my huge project since once you open it - the indexing will last 2 hours. When I'll buy a laptop it will be literally hell. Maybe introduce lazy mode - index one file every time you open it?

**Comment by Riatre** [comment] 2018-12-27 07:43
I believe adding ".*" to initialBlacklist is effectively "index one file every time you open it", I agree this is not obvious though.

**Comment by Yanpas** [comment] 2018-12-27 08:09
Extension can gain command "restart in lazy mode" which will restart ccls and override initialBlacklist with this regex. I think it will be sufficient.

**Comment by MaskRay** [comment] 2018-12-27 08:47
Restarting ccls with `index.initialBlacklist` changed is the simplest approach.

Extending `workspace/didChangeConfiguration` to allow updating `Config *g_config` (`settings.initializationOptions.index.initialBlacklist`) may be favored by some people, but it is not simple. There are several design choices, e.g.

* `g_config` itself is made atomic. Each use site needs to grab a snapshot first.
* Protect `g_config` options that can be updated with one or more mutexes: cluttering existing code.

**Comment by Yanpas** [comment] 2018-12-27 08:54
Let's imagine I've surrounded g_config with shared mutex. What will happen in the following scenario(I don't know internals of ccls)? :
* User started ccls, it shows that 5000 jobs remaining and runs four parralel compilcation jobs
* Then user runs our magic command that alters initialBlacklist

Will the remaining 5000 jobs be cancelled and threadpool become idle?

**Comment by MaskRay** [comment] 2018-12-27 09:09
https://github.com/maskray/ccls/blob/master/src/project.cc#L504

`index.initialBlacklist` is only read in `ccls::Project::Index` and the function is called by `initialize`, `$ccls/reload` `workspace/didChangeConfiguration` `workspace/didChangeWorkspaceFolders` (how VSCode handles workspace folders is very unclear to me. I'm very confused by its naming: "Open Folder" "Open Workspace" "Close Folder" ...).

**Comment by madscientist** [comment] 2018-12-28 17:10
I'm visiting family for holidays so I'm only sporadically available.

What I'm trying to do is come up with a configuration that can be handed out mostly as-is to people who don't want to do a lot of customization, and can provide great out-of-the-box behavior even on large codebases.  I understand your suggestion of jumping from the use to the declaration to the definition.  I personally would prefer to have these sorts of things magically handled behind the scenes but obviously we have to balance efforts.

Basically I'm trying to find a way to configure ccls and Emacs where I can avoid an expensive indexing operation kicked off by default the first time I visit a new worktree, and still get as much utility as possible AND provide clear behavior (e.g., make it clear what features you get without full indexing and which you don't, and make it simple for people to switch to full indexing).

> If a common header bar.h is included by both foo0.c and foo1.c, what's the distance from foo0.c to foo1.c assuming other edges do not exist?

The distance I was defining refers to usage and definition relationships.  So two files are related with a distance of 1 if file A _uses_ a symbol _defined_ in file B.  File A has a distance of 2 from file C if A uses a symbol defined in B (but no symbols defined in C), and B uses a symbol defined in C.  Maybe any distance above 1 is not really useful, so maybe "distance" as a term is not that helpful.

Maybe it's enough to provide a way to index files "one level removed" from any file visited (that is, files that define symbols declared in headers that a file includes) and we don't need further "levels" than that.

**Comment by MaskRay** [comment] 2018-12-28 19:34
>  If I run command ccls_reload (Reload index in vs code) three times - ccls shows number (res['pipeline']['pendingIndexRequests']) three times higher than entries in my compile_commands

This is the expected behavior. `$ccls/reload` is like a lightweight "restarting ccls". Invoking `$ccls/reload` adds N index tasks where N is the number of `compile_commands.json` entries + recursive file listing (if `.ccls` was used when ccls started). Don't worry much about the number of index tasks, because there will not be actual parsing if the cached files are not invalidated (you'll find `load cache for ...` instead of `store index for ...` in the `-log-file` file)

>

**Comment by Yanpas** [comment] 2018-12-29 14:35
> Invoking $ccls/reload adds N index tasks

> because there will not be actual parsing if the cached files are not invalidated

So If I have an empty cache and run workspace/didChangeConfiguration with initialBlackList setting I will still have to wait while all files will be indexed.

**Closed** 2018-12-30 02:09 UTC

**Comment by cmm** [comment] 2018-12-30 16:14
Instead of dubious file name heuristics, how about just giving the user a way to explicitly rate-limit the indexer?  Say, 2 parameters, one being "cap the initial indexing load at this number" and the other being "shut down initial indexing after this number of seconds since the last request"?

**Comment by madscientist** [comment] 2018-12-30 16:32
I'm not sure I see the point in that.  In this situation we have a very large codebase (else why disable indexing).  So what's the advantage to indexing some random portion of the codebase which may or may not have any relation to the files we're editing?  That doesn't seem like a fruitful use of resources.  What we want is to have the best chance of operations like "jump to definition" working properly (because the definition was indexed).

The goal of the filename heuristic is to give the best chance of indexing portions of the codebase which are actually related to the files that are being edited, without having to index everything.  The heuristic may be dubious in some projects but I think it's very likely to be quite accurate in most.  I've never run across a project of any significant size where the implementation was not kept in source files related to headers by file name.

However if you can think of a better way to discover relevant files to index, that would be great!

**Comment by cmm** [comment] 2018-12-30 16:52
I don't really have a problem with heuristics, especially ones that are statistically likely to work, but it helps to keep in mind what problem is being solved.  Perhaps I misunderstood yours, which I now take to be "there's a fresh tree, I intend to spend some quality time in it, but it would be great if the indexer tried to be actually useful to whatever I'm doing right now".  The filename heuristic is fine for that, in fact any heuristic would be better than nothing.

The thing that has bitten me, on the other hand, is more like "so I've made a new git work tree for some quick bug fix, why is my computer suddenly very hot and not very responsive" -- i.e. the emphasis here is less on directing the indexer, and more on preventing it from eating resources.

And, of course, explicit rate limiting and heuristics don't contradict each other at all -- it would be great if the rate-limited background indexing process were smarter than just going in the order of compile_command.json or whatever...

**Comment by madscientist** [comment] 2018-12-31 02:35
There are existing ways to reduce indexing.  You can use the index.initialBlacklist to disable default indexing of all files other than files you actually visit, or to avoid default indexing of areas of the code you rarely use.  You can also reduce the number of cores used during indexing via the index.threads setting.

That doesn't allow a feature like "index 100 files then stop" or similar such as you suggest, but I just don't see the point of that kind of feature unless it's combined with a way to determine which files are most likely to be interesting.  Otherwise sure, you're reducing the overhead of the indexing but you've just indexed 100 random files which are probably irrelevant.  I think setting index.initialBlacklist to match all files (to index nothing by default) would be a better solution.
